### PR TITLE
Remove build system for sip v4

### PR DESCRIPTION
**Pull request by jeanas**
The last bugfix release of sip 4 was in February 2018, 5 years ago. Even sip 5 is now unsupported. It should be safe to remove the parallel build system for sip 4 in favor of the sip 5/6 build system defined in pyproject.toml and project.py, avoiding the need to maintain two build systems in parallel.

### CODE REVIEW

**Comment by fedelibre** [comment]
Can you also bump the minimum sip version required in the INSTALL file? (while on it I would also remove the `(tested with 2.6)` referred to Python)

**Comment by jeanas** [comment]
Thanks for reminding me.

**Comment by jeanas** [comment]
Let’s merge it?

**Comment by fedelibre** [comment]
Ok, go ahead

**Pull request merged**
